import { saveProfile, type Profile } from "./profiles";

const SEED_PROFILES: Profile[] = [
  // ============ MEN (15) ============
  {
    id: "seed_m_01",
    firstName: "Marcus",
    lastName: "Chen",
    email: "marcus.chen@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1996",
    state: "California",
    height: "5'11\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Intellectual discussions", "Cooking", "Travel", "Podcasts", "Reading"],
    topCharacteristics: ["Honest", "Emotionally mature", "Ambitious", "Patient", "Open-minded"],
    socialLink: "https://i.pravatar.cc/400?img=3",
    answers: {
      unconventional_path: "Left a six-figure consulting job to go to culinary school at 27. Everyone thought I was having a quarter-life crisis, but I'd been cooking my way through every cuisine since college. Now I run a pop-up dinner series that merges Asian and Mexican flavors. Best decision I ever made.",
      fascination: "The science of fermentation. I can talk about koji mold, lacto-fermentation, and the microbiology of sourdough for literal hours. My friends' eyes glaze over but I don't care.",
      humor: "My buddy tried to impress a date by cooking her a fancy meal, set off the smoke alarm three times, and the fire department actually showed up. He answered the door in an apron that said 'Kiss the Cook.' She married him.",
      admired_quality: "When someone is genuinely excellent at something but doesn't need to tell you about it. You just watch them work and realize they're operating on another level. Quiet mastery.",
      growth_edge: "Learning to be present instead of always optimizing. I have a tendency to treat life like a series of projects. Working on just sitting with things.",
      friend_pitch: "Marcus is the guy who remembers your favorite drink, asks about the thing you mentioned three weeks ago, and will drive across town at midnight if you need him. Also he'll cook you the best meal of your life.",
      prompt_ted_talk: "Why the best innovations happen when you combine two unrelated fields — like molecular gastronomy and street food",
      prompt_controversial: "Most 'foodie' culture is just performance. The best food in any city is at a strip mall or a grandma's kitchen, not the place with the Instagram wall.",
      prompt_secret_talent: "I can identify almost any spice blindfolded. My friends test me at parties and I haven't lost yet.",
    },
    vectors: {
      selfExpansion: ["Culinary innovation", "Cross-cultural food fusion", "Fermentation science", "Entrepreneurial cooking"],
      admirationSignals: ["Career pivot courage", "Deep craft mastery", "Loyal and present friend"],
      humorSignature: "Warm storytelling humor — finds the absurd in everyday situations and tells it with perfect timing",
      growthTrajectory: "Moving from achievement-oriented living toward presence and deeper connection",
      iSharingMarkers: ["Discovering a perfect hole-in-the-wall restaurant", "Spontaneous deep conversations over food", "The moment an experiment works"],
    },
    eloScore: 1280,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_02",
    firstName: "James",
    lastName: "Whitfield",
    email: "james.w@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1992",
    state: "Colorado",
    height: "6'2\"",
    education: "Bachelor's",
    exercise: "5-6x/week",
    interests: ["Outdoor sports", "Nature", "Photography", "Camping", "Writing"],
    topCharacteristics: ["Honest", "Calm", "Patient", "Open-minded", "Creative"],
    socialLink: "https://i.pravatar.cc/400?img=7",
    answers: {
      unconventional_path: "Dropped out of law school after one semester. Everyone said I was throwing away my future. Became a wilderness guide instead and now run a backcountry photography workshop business. I make less money but I wake up in places most people only see in screensavers.",
      fascination: "Avalanche science and snowpack analysis. It's this incredible intersection of physics, weather patterns, and terrain that can save your life if you understand it.",
      humor: "Led a group of corporate execs on a 'team building' backcountry trip. Their CEO, this very serious guy, got his boot stuck in a mud bog and just slowly sank while giving a motivational speech. He committed to the speech the whole time. Standing ovation from the mud.",
      admired_quality: "People who can sit in silence comfortably. Not awkward silence — just being present together without needing to fill every moment with noise.",
      growth_edge: "Getting better at vulnerability in relationships. I'm great at being strong and capable in the wilderness but I've learned that's not the same as being emotionally available.",
      friend_pitch: "James is the most grounded human being you'll ever meet. He'll take you on an adventure that changes how you see the world, and then cook you dinner over a campfire while asking the kind of questions that make you think for days.",
      prompt_ted_talk: "How spending time in genuine wilderness rewires your nervous system and makes you a better partner",
      prompt_controversial: "Most people don't actually want adventure — they want the aesthetic of adventure. There's a huge difference between a curated camping photo and sleeping through a thunderstorm at 12,000 feet.",
      prompt_secret_talent: "I can predict weather changes by reading clouds and wind patterns about 6-8 hours out. More accurate than most apps.",
    },
    vectors: {
      selfExpansion: ["Backcountry wilderness", "Nature photography", "Avalanche science", "Outdoor leadership"],
      admirationSignals: ["Chose authenticity over prestige", "Deep environmental knowledge", "Calm under extreme pressure"],
      humorSignature: "Deadpan observational humor — notices absurd contrasts between nature and human behavior",
      growthTrajectory: "Learning emotional vulnerability to match his physical and intellectual courage",
      iSharingMarkers: ["Watching a sunset in complete silence", "Surviving something challenging together", "The first morning in a new wild place"],
    },
    eloScore: 1350,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_03",
    firstName: "Devon",
    lastName: "Baptiste",
    email: "devon.b@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1998",
    state: "New York",
    height: "5'9\"",
    education: "Bachelor's",
    exercise: "3-4x/week",
    interests: ["Musical instruments", "Social issues", "Volunteering", "Podcasts", "Startups"],
    topCharacteristics: ["Empathetic", "Ambitious", "Creative", "Funny", "Spontaneous"],
    socialLink: "https://i.pravatar.cc/400?img=11",
    answers: {
      unconventional_path: "Started a nonprofit music program in my neighborhood when I was 19 with zero funding. Everyone said I was too young and it would fail. Five years later, 200 kids have come through the program and three of them got music scholarships.",
      fascination: "The intersection of music therapy and neuroscience. How rhythm literally rewires neural pathways in kids with trauma. It's not woo-woo — it's measurable brain change.",
      humor: "I was teaching a 7-year-old drums and he just stopped mid-lesson, looked me dead in the eye, and said 'Devon, I think you need to practice more.' The whole class lost it. He wasn't wrong.",
      admired_quality: "When someone channels their anger about injustice into building something instead of just complaining. Productive rage is the most attractive quality.",
      growth_edge: "Learning to delegate and let go of control. My nonprofit is growing and I can't do everything myself anymore, but every time someone does something differently than I would, I have to physically stop myself from taking over.",
      friend_pitch: "Devon has more energy than anyone you'll ever meet and he uses all of it to make the world slightly less broken. He'll make you laugh, make you think, and probably convince you to volunteer for something by the end of the first date.",
      prompt_ted_talk: "Why every kid deserves access to an instrument, and the neuroscience that proves music changes brains",
      prompt_controversial: "Charity galas are mostly rich people congratulating each other. The real impact happens in unglamorous rooms with unglamorous budgets.",
      prompt_secret_talent: "I can beatbox and play piano at the same time. It's ridiculous and impressive in equal measure.",
    },
    vectors: {
      selfExpansion: ["Music education", "Youth development", "Nonprofit leadership", "Music therapy neuroscience"],
      admirationSignals: ["Built something from nothing at 19", "Channels passion into impact", "Natural teacher and mentor"],
      humorSignature: "High-energy, self-deprecating humor with perfect comedic timing from years of working with kids",
      growthTrajectory: "Evolving from doer to leader — learning to build systems that outlast his personal effort",
      iSharingMarkers: ["Watching someone discover they can do something they thought they couldn't", "Spontaneous jam sessions", "The moment a room full of people laughs together"],
    },
    eloScore: 1180,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_04",
    firstName: "Ethan",
    lastName: "Park",
    email: "ethan.park@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1994",
    state: "Washington",
    height: "5'10\"",
    education: "Doctorate",
    exercise: "1-2x/week",
    interests: ["Reading", "Gaming", "Intellectual discussions", "Cooking", "TV/Movies"],
    topCharacteristics: ["Logical", "Patient", "Honest", "Funny", "Open-minded"],
    socialLink: "https://i.pravatar.cc/400?img=14",
    answers: {
      unconventional_path: "Published a paper in Nature at 26 that challenged a pretty established theory in computational biology. My advisor told me I was committing career suicide. Three years later it's been cited 400 times and the field shifted.",
      fascination: "How proteins fold. It sounds boring but it's literally the most complex origami in the universe and it governs everything from why you get sick to how your brain works.",
      humor: "My lab partner once accidentally set his eyebrows on fire and his first reaction was to calmly say 'well, that's one way to do a hot take.' We had to evacuate the building and he was still making puns in the parking lot.",
      admired_quality: "Intellectual honesty — when someone can say 'I was wrong' or 'I don't know' without their ego imploding. It's shockingly rare, even among smart people.",
      growth_edge: "Being more spontaneous. I tend to over-plan everything. My friends joke that I'd schedule a spontaneous adventure three weeks in advance.",
      friend_pitch: "Ethan is the person you want in your corner when you need to think through a hard problem, but also the person who'll make you snort-laugh with the nerdiest joke you've ever heard. He cooks a mean Korean BBQ and his movie taste is impeccable.",
      prompt_ted_talk: "How AI is revolutionizing protein structure prediction, and why that matters for every human on Earth",
      prompt_controversial: "Most popular science communication is so dumbed down it actually makes people less scientifically literate. We need to trust people with complexity.",
      prompt_secret_talent: "I'm unreasonably good at strategy board games. I've won three regional Settlers of Catan tournaments.",
    },
    vectors: {
      selfExpansion: ["Computational biology", "Protein science", "Scientific publishing", "Strategy gaming"],
      admirationSignals: ["Challenged established science and was right", "Deep intellectual rigor", "Humble about genuine achievements"],
      humorSignature: "Dry, nerdy wit — the kind of humor that sneaks up on you three seconds after the punchline",
      growthTrajectory: "Learning to let go of control and embrace the unplanned moments of life",
      iSharingMarkers: ["The 'aha' moment when a concept clicks", "Debating ideas without ego", "Sharing a perfectly cooked meal"],
    },
    eloScore: 1100,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_05",
    firstName: "Rafael",
    lastName: "Morales",
    email: "rafe.m@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1990",
    state: "Texas",
    height: "6'0\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Social issues", "Reading", "Dancing", "Cooking", "Travel"],
    topCharacteristics: ["Empathetic", "Responsible", "Honest", "Confident", "Ambitious"],
    socialLink: "https://i.pravatar.cc/400?img=52",
    answers: {
      unconventional_path: "Left BigLaw after 2 years to start an immigration legal clinic in my hometown. Took a 70% pay cut. My parents had gone through the immigration system themselves and I watched a generation of kids grow up not knowing if their families would be torn apart. I couldn't keep billing hours for corporations.",
      fascination: "Constitutional law history — specifically how the same amendment can be interpreted completely differently across decades. The Constitution is a living argument, not a document.",
      humor: "I was in court making what I thought was a very compelling argument and my phone alarm went off playing Bad Bunny at full volume. The judge just looked at me and said 'Counselor, I didn't know you had such good taste.' I won the case.",
      admired_quality: "Moral courage — people who do the right thing when it costs them something. It's easy to have values when they're convenient.",
      growth_edge: "Work-life boundaries. I care so much about my clients that I've let it consume me. Learning that I can't pour from an empty cup.",
      friend_pitch: "Rafe is the most principled person I know, but he's not preachy about it. He's the guy who makes everyone at the table feel heard, dances like nobody's watching (and he's actually good), and will fight for you literally and figuratively.",
      prompt_ted_talk: "How the immigrant experience shaped American innovation — and why closing doors costs us all",
      prompt_controversial: "Pro bono work shouldn't be charity — it should be a requirement for every licensed attorney. The legal system is broken because access is a luxury.",
      prompt_secret_talent: "I'm a really good salsa dancer. Like, competition-level. Nobody expects it from the lawyer.",
    },
    vectors: {
      selfExpansion: ["Immigration law", "Social justice", "Latin dance culture", "Constitutional law history"],
      admirationSignals: ["Sacrificed prestige for purpose", "Deep moral courage", "Bridges professional excellence with compassion"],
      humorSignature: "Effortlessly charming humor — finds levity in high-stakes situations without diminishing them",
      growthTrajectory: "Learning to sustain himself so he can sustain his mission long-term",
      iSharingMarkers: ["Dancing without self-consciousness", "Conversations about what really matters", "Witnessing justice happen in real time"],
    },
    eloScore: 1420,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_06",
    firstName: "Theo",
    lastName: "Andersson",
    email: "theo.a@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1995",
    state: "Oregon",
    height: "6'1\"",
    education: "Bachelor's",
    exercise: "5-6x/week",
    interests: ["Outdoor sports", "Craft projects", "Photography", "Camping", "Animals"],
    topCharacteristics: ["Calm", "Patient", "Creative", "Honest", "Flexible"],
    socialLink: "https://i.pravatar.cc/400?img=53",
    answers: {
      unconventional_path: "Quit my desk job to become a furniture maker. Apprenticed under a 70-year-old Japanese woodworker for two years. He barely spoke English and I barely spoke Japanese. We communicated through the wood. Sounds pretentious but it's literally what happened.",
      fascination: "Wood grain patterns and how a tree's life story is written in its rings. I can look at a cross-section and tell you about droughts, fires, good years. Every piece of wood is a biography.",
      humor: "My dog once ate an entire batch of sourdough starter and spent the next 24 hours with the most confused expression I've ever seen on any living creature. The bread literally rose inside him. He was fine but I've never seen a more philosophical dog.",
      admired_quality: "Patience in craft — when someone has clearly spent thousands of hours perfecting something not because it's profitable but because it matters to them.",
      growth_edge: "Being more assertive about my own needs. I'm so easygoing that I sometimes let people walk all over me. My therapist calls it 'aggressive agreeableness.'",
      friend_pitch: "Theo is the most quietly talented person you'll ever meet. He builds beautiful furniture, takes incredible photos, and has this calming energy that makes everything feel less hectic. Also his dog is the best wingman.",
      prompt_ted_talk: "What a 70-year-old woodworker taught me about patience, mastery, and communicating without words",
      prompt_controversial: "We've lost the ability to sit with boredom, and it's making us worse at everything. Your best ideas come when you're doing nothing.",
      prompt_secret_talent: "I can carve a spoon from a raw piece of wood in under 20 minutes. It's my party trick, except the parties I go to are in workshops.",
    },
    vectors: {
      selfExpansion: ["Japanese woodworking", "Furniture craftsmanship", "Nature photography", "Contemplative living"],
      admirationSignals: ["Cross-cultural apprenticeship", "Deep patience and craft mastery", "Authentic simplicity"],
      humorSignature: "Gentle, observational humor — finds warmth in small absurdities of daily life",
      growthTrajectory: "Learning to advocate for himself while maintaining his peaceful nature",
      iSharingMarkers: ["Working with hands in comfortable silence", "Discovering beauty in natural details", "Moments of quiet awe"],
    },
    eloScore: 1200,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_07",
    firstName: "Jordan",
    lastName: "Brooks",
    email: "jordan.b@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1997",
    state: "Georgia",
    height: "5'8\"",
    education: "Bachelor's",
    exercise: "3-4x/week",
    interests: ["Startups", "Gaming", "Podcasts", "Working out", "TV/Movies"],
    topCharacteristics: ["Ambitious", "Funny", "Confident", "Spontaneous", "Creative"],
    socialLink: "https://i.pravatar.cc/400?img=55",
    answers: {
      unconventional_path: "Built a mobile game in my dorm room that got 2 million downloads. Used the money to fund my actual passion — a platform connecting local Black-owned businesses with customers. It's not as sexy as gaming but it's what I actually care about.",
      fascination: "Behavioral economics and why people make irrational decisions. I've read everything Kahneman and Thaler ever wrote and I use it in product design daily.",
      humor: "I pitched my startup to a VC and midway through my computer died. I just stood there and did the entire pitch from memory, drawing diagrams on a napkin. The VC said it was the best pitch he'd ever seen. I think the panic gave me superpowers.",
      admired_quality: "Resourcefulness — when someone makes something amazing from limited resources. Anyone can build cool stuff with unlimited funding. Show me what you do with nothing.",
      growth_edge: "Slowing down. I have a tendency to move at 100 mph and sometimes I miss things — details, feelings, moments. Learning to be in the moment instead of three steps ahead.",
      friend_pitch: "Jordan is the most fun person in any room but he's also low-key building an empire. He'll challenge you intellectually, make you laugh until you cry, and probably have three business ideas before dessert.",
      prompt_ted_talk: "Why the most important startups aren't in Silicon Valley — they're in underserved communities",
      prompt_controversial: "Hustle culture is a scam sold by people who already have generational wealth. Real entrepreneurship is about solving problems, not grinding yourself to dust.",
      prompt_secret_talent: "I do impressions. Really good ones. My Obama is apparently 'unsettling in its accuracy.'",
    },
    vectors: {
      selfExpansion: ["Tech entrepreneurship", "Behavioral economics", "Community commerce", "Mobile gaming"],
      admirationSignals: ["Built multiple ventures before 25", "Redirected success toward community impact", "Thrives under pressure"],
      humorSignature: "High-energy, performance-style humor — charismatic storytelling with killer impressions",
      growthTrajectory: "Learning to slow down and prioritize depth over breadth in both work and relationships",
      iSharingMarkers: ["Riffing on ideas together", "Spontaneous adventures", "The moment a plan comes together"],
    },
    eloScore: 1050,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_08",
    firstName: "Oliver",
    lastName: "Sinclair",
    email: "oliver.s@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1991",
    state: "Massachusetts",
    height: "5'10\"",
    education: "Master's / JD",
    exercise: "1-2x/week",
    interests: ["Reading", "Art", "Museums", "Theatre", "Writing"],
    topCharacteristics: ["Emotionally mature", "Empathetic", "Creative", "Patient", "Intuitive"],
    socialLink: "https://i.pravatar.cc/400?img=57",
    answers: {
      unconventional_path: "I was on track to be a literature professor and instead became a grief counselor. My best friend died when we were 23 and I realized I'd spent my life studying human emotions in books but had no idea how to actually sit with them. Changed my entire path.",
      fascination: "How different cultures process grief. In Ghana, funerals are celebrations. In Japan, there's a word — mono no aware — for the bittersweet awareness of impermanence. Americans are terrible at grief and I think it makes us terrible at love too.",
      humor: "A client once told me I looked 'exactly like a therapist would look if a therapist was ordered from Wish.' I still think about it weekly. They weren't wrong.",
      admired_quality: "Emotional courage — people who say the hard thing with kindness. Not brutal honesty (that's usually just brutality) but genuine, compassionate truth-telling.",
      growth_edge: "Letting people take care of me. I'm so used to being the person who holds space for others that I forget I need space held for me too.",
      friend_pitch: "Oliver is the person who makes you feel truly seen. He asks questions nobody else thinks to ask and genuinely listens to the answers. He's also hilarious in the driest possible way, writes beautifully, and gives the best book recommendations.",
      prompt_ted_talk: "Why learning to grieve well is the key to loving well — and why we need to talk about death more",
      prompt_controversial: "Self-help culture has made us afraid of negative emotions. Sadness, anger, and grief aren't problems to solve — they're essential parts of being alive.",
      prompt_secret_talent: "I write poetry that I've never shown anyone. I have three notebooks full. One day.",
    },
    vectors: {
      selfExpansion: ["Grief counseling", "Cross-cultural death practices", "Literary analysis", "Emotional intelligence"],
      admirationSignals: ["Transformed personal tragedy into purpose", "Rare emotional depth", "Holds space for others with grace"],
      humorSignature: "Bone-dry, self-aware humor — the therapist who can laugh at himself and the human condition",
      growthTrajectory: "Learning to receive care as gracefully as he gives it",
      iSharingMarkers: ["Conversations that go deeper than expected", "Sharing a beautiful piece of writing", "Comfortable silence that feels like connection"],
    },
    eloScore: 1300,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_09",
    firstName: "Liam",
    lastName: "O'Connell",
    email: "liam.oc@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1993",
    state: "Illinois",
    height: "6'3\"",
    education: "Bachelor's",
    exercise: "5-6x/week",
    interests: ["Working out", "Cooking", "Travel", "Volunteering", "Animals"],
    topCharacteristics: ["Responsible", "Honest", "Calm", "Forgiving", "Empathetic"],
    socialLink: "https://i.pravatar.cc/400?img=59",
    answers: {
      unconventional_path: "Became a firefighter paramedic after college instead of using my finance degree. My dad was a trader and wanted me to follow him. But I volunteered as an EMT in college and realized I needed to do something where I could feel the impact of my work directly, not on a spreadsheet.",
      fascination: "Emergency medicine triage — the split-second decision-making that happens when you arrive at a scene. How do you prioritize when everything is urgent? It's a cognitive skill most people never develop.",
      humor: "We got called to a 'structure fire' and it turned out to be a guy who'd tried to flambé bananas foster for the first time. His kitchen was fine, he was fine, but his eyebrows were gone and his cat was sitting on top of the fridge looking at him with pure contempt.",
      admired_quality: "Grace under pressure. Not flashy heroism — just the quiet ability to stay calm when everything is going wrong and make good decisions anyway.",
      growth_edge: "Opening up emotionally. My job requires compartmentalization and I've gotten too good at it. Working on bringing the walls down in my personal life.",
      friend_pitch: "Liam is a golden retriever in human form but with the competence of someone who literally saves lives for a living. He'll cook you an incredible meal, fix whatever's broken in your apartment, and somehow make you feel safe just by being in the room.",
      prompt_ted_talk: "How first responders develop decision-making under extreme uncertainty — and what everyone can learn from it",
      prompt_controversial: "We romanticize first responders but underpay and under-support them. 'Thank you for your service' means nothing without policy change.",
      prompt_secret_talent: "I bake incredible sourdough bread. The fire station has a 48-hour shift schedule that's perfect for sourdough timing.",
    },
    vectors: {
      selfExpansion: ["Emergency medicine", "Fire service culture", "Sourdough artistry", "Crisis decision-making"],
      admirationSignals: ["Chose impact over income", "Calm under extreme pressure", "Genuine service orientation"],
      humorSignature: "First responder humor — finds lightness in intense situations, warm and self-effacing",
      growthTrajectory: "Learning to be emotionally vulnerable after years of professional compartmentalization",
      iSharingMarkers: ["Cooking together at home", "Quiet evenings after intense days", "Helping someone and seeing it matter"],
    },
    eloScore: 1380,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_10",
    firstName: "Noah",
    lastName: "Kim",
    email: "noah.kim@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1999",
    state: "California",
    height: "5'7\"",
    education: "Bachelor's",
    exercise: "3-4x/week",
    interests: ["Art", "Photography", "Fashion", "Travel", "Singing"],
    topCharacteristics: ["Creative", "Spontaneous", "Confident", "Open-minded", "Intuitive"],
    socialLink: "https://i.pravatar.cc/400?img=60",
    answers: {
      unconventional_path: "Turned down a product design job at Apple to freelance as a creative director. My portfolio was all passion projects — album covers for local musicians, branding for food trucks, zines. I wanted to make art, not products. Still do.",
      fascination: "Typography and how font choices subconsciously shape perception. The same sentence in Helvetica vs. Garamond communicates completely different things. Most people don't notice but it controls how you feel about everything you read.",
      humor: "I was shooting a wedding and the flower girl decided mid-ceremony that she was done participating. She sat down in the aisle, took off her shoes, and started eating Cheerios from her pocket. The bride was crying laughing. Best wedding photo I've ever taken.",
      admired_quality: "When someone has a completely original eye — they see beauty or meaning in things that everyone else walks past. Artists, sure, but also anyone who notices the world differently.",
      growth_edge: "Financial stability. I chose the creative life and I love it, but I'm learning to build sustainable systems instead of lurching between feast and famine.",
      friend_pitch: "Noah will take you to the coolest places you've never heard of, make everything look beautiful, and see things about you that you didn't even see about yourself. He's the most visually creative person I know and he's surprisingly deep once you get past the aesthetic.",
      prompt_ted_talk: "Why 'good taste' is actually a learnable skill, not a born trait — and how to develop your visual eye",
      prompt_controversial: "Instagram has democratized photography but destroyed visual literacy. Everyone can take a pretty picture now but almost nobody can tell you why it works.",
      prompt_secret_talent: "I can draw a near-perfect portrait of someone in about 5 minutes. I used to do caricatures at fairs as a teenager.",
    },
    vectors: {
      selfExpansion: ["Visual design world", "Typography and branding", "Underground arts scene", "Creative freelancing"],
      admirationSignals: ["Chose artistic integrity over prestige", "Original visual perspective", "Sees beauty others miss"],
      humorSignature: "Observational and visual — notices absurd details and frames life like a photographer",
      growthTrajectory: "Building financial sustainability without compromising creative authenticity",
      iSharingMarkers: ["Discovering a beautiful detail nobody else noticed", "Creating something together", "Wandering a new city with no plan"],
    },
    eloScore: 960,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_11",
    firstName: "Caleb",
    lastName: "Washington",
    email: "caleb.w@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1988",
    state: "Tennessee",
    height: "6'0\"",
    education: "Vocational / trade",
    exercise: "3-4x/week",
    interests: ["Musical instruments", "Faith/Spirituality", "Cooking", "Volunteering", "Nature"],
    topCharacteristics: ["Patient", "Forgiving", "Empathetic", "Responsible", "Honest"],
    socialLink: "https://i.pravatar.cc/400?img=61",
    answers: {
      unconventional_path: "After getting sober at 25, I started mentoring kids in recovery. Everyone told me I needed to 'focus on myself first' but helping others was how I focused on myself. Now I run a mentorship program and I'm 13 years sober.",
      fascination: "Blues music history — the migration from Delta to Chicago, how an entire art form carried the emotional weight of a people. Every blues song is a therapy session set to a 12-bar structure.",
      humor: "I was grilling at a church cookout and a kid asked me if I was 'the best cook in the world.' I said yes, obviously. He took one bite of my burger and said 'I've had better at McDonald's.' Just destroyed me in front of God and everyone.",
      admired_quality: "Genuine transformation — when someone has been through something hard and come out the other side not bitter but genuinely softer and wiser. That's earned wisdom.",
      growth_edge: "Trusting that good things can last. I've gotten good at surviving hard things but I'm still learning to enjoy good things without waiting for the other shoe to drop.",
      friend_pitch: "Caleb has lived more life than most people twice his age and it made him the kindest person you'll ever meet. He plays guitar that'll make you cry, grills like a champion, and has this quiet strength that makes you feel like everything's going to be okay.",
      prompt_ted_talk: "What recovery taught me about vulnerability, community, and why the strongest people are the ones who ask for help",
      prompt_controversial: "The self-improvement industry has monetized human suffering. Real growth is messy, communal, and usually free. You don't need a $2000 course to become a better person.",
      prompt_secret_talent: "I can tune a guitar by ear perfectly. No tuner, no reference pitch. Just decades of playing.",
    },
    vectors: {
      selfExpansion: ["Recovery mentorship", "Blues music tradition", "Southern cooking culture", "Faith community"],
      admirationSignals: ["13 years of sobriety and service", "Transformed pain into purpose", "Earned wisdom through lived experience"],
      humorSignature: "Self-deprecating Southern warmth — humble, earthy humor rooted in real life",
      growthTrajectory: "Learning to receive joy and trust in sustained happiness after years of survival mode",
      iSharingMarkers: ["Listening to live blues in a small venue", "Honest late-night conversations", "The feeling of community around a shared meal"],
    },
    eloScore: 1250,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_12",
    firstName: "Aiden",
    lastName: "Shah",
    email: "aiden.shah@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1996",
    state: "New Jersey",
    height: "5'9\"",
    education: "Master's / JD",
    exercise: "1-2x/week",
    interests: ["Intellectual discussions", "Startups", "Podcasts", "Travel", "Cooking"],
    topCharacteristics: ["Ambitious", "Logical", "Confident", "Funny", "Open-minded"],
    socialLink: "https://i.pravatar.cc/400?img=12",
    answers: {
      unconventional_path: "Left my PhD program one year before finishing to join a healthcare AI startup. My professors were horrified. But I realized I'd rather solve one real problem imperfectly than publish perfect papers nobody reads. We've since helped 50,000 patients get faster diagnoses.",
      fascination: "The philosophy of consciousness — specifically the hard problem. Why does subjective experience exist at all? We can map every neuron and still can't explain why red looks like red to you.",
      humor: "I tried to explain my startup to my Indian grandmother. After 20 minutes she patted my hand and said 'Beta, so you work with computers.' I'd just raised $4M and she summed it up perfectly.",
      admired_quality: "First-principles thinking — when someone can strip away all assumptions and rebuild their understanding from scratch. It's rare and it's how every real breakthrough happens.",
      growth_edge: "Being present in conversations instead of thinking about the next thing. My mind runs fast and I've been told I can seem distracted even when I care deeply.",
      friend_pitch: "Aiden is the smartest person in most rooms but the last person who'd tell you that. He'll have three interesting ideas before you've finished your coffee, send you the perfect article at 2am, and remember every detail of the thing you told him about your life.",
      prompt_ted_talk: "Why the next trillion-dollar company will be built by someone who deeply understands suffering, not technology",
      prompt_controversial: "Most AI ethics discussions are theater. The real ethical question isn't 'should we build this' — it's 'who gets to decide, and who benefits.'",
      prompt_secret_talent: "I can solve a Rubik's cube in under 90 seconds. Learned it during a boring summer internship.",
    },
    vectors: {
      selfExpansion: ["Healthcare AI", "Consciousness philosophy", "Startup building", "First-principles thinking"],
      admirationSignals: ["Left academia to solve real problems", "Impact-driven at scale", "Humble about significant achievements"],
      humorSignature: "Intellectual humor that's surprisingly self-aware — the nerd who can laugh at nerd culture",
      growthTrajectory: "Learning to be fully present instead of perpetually future-oriented",
      iSharingMarkers: ["Mind-bending 'what if' conversations", "The rush of solving something together", "Discovering unexpected connections between ideas"],
    },
    eloScore: 1150,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_13",
    firstName: "Diego",
    lastName: "Reyes",
    email: "diego.r@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1993",
    state: "Arizona",
    height: "5'11\"",
    education: "Bachelor's",
    exercise: "5-6x/week",
    interests: ["Outdoor sports", "Travel", "Photography", "Dancing", "Cooking"],
    topCharacteristics: ["Spontaneous", "Confident", "Funny", "Flexible", "Optimistic"],
    socialLink: "https://i.pravatar.cc/400?img=8",
    answers: {
      unconventional_path: "Sold everything I owned at 25 and spent two years traveling through South America as a climbing and kayaking guide. When I came back, I started an outdoor adventure company that takes people from underserved communities on their first wilderness trips. Everyone said you can't make a business out of that. We're in our fifth year.",
      fascination: "Rock climbing route-setting — it's like writing a physical puzzle that communicates through your body. A great route tells a story: struggle, discovery, triumph. It's choreography on stone.",
      humor: "I was leading a group of teenagers on their first rock climb and this kid who'd been terrified the whole time reached the top and screamed 'I'M THE CAPTAIN NOW' in a perfect movie voice. Every guide cried laughing. He's now one of our volunteer leaders.",
      admired_quality: "Joy that's contagious. When someone's genuine excitement makes everyone around them more excited. Not performative — the real, bubbling-over kind.",
      growth_edge: "Sitting still. I'm great at motion and adventure but I'm learning that some of the best parts of life happen when you stop moving.",
      friend_pitch: "Diego is the human embodiment of 'yes, and.' He'll turn a Tuesday into an adventure, cook you incredible food with whatever's in the fridge, and somehow make everyone around him braver just by being there.",
      prompt_ted_talk: "Why access to wilderness is a social justice issue — and how adventure changes who you believe you can be",
      prompt_controversial: "The outdoor industry has a massive diversity problem and most companies' 'initiatives' are marketing, not change. If your board is all white, your values statement is fiction.",
      prompt_secret_talent: "I can make an incredible meal from literally any 5 random ingredients. My friends call it 'Chopped: Diego Edition.'",
    },
    vectors: {
      selfExpansion: ["Wilderness adventure", "Rock climbing culture", "Social impact outdoors", "Latin American travel"],
      admirationSignals: ["Built purpose-driven adventure business", "Contagious joy and courage", "Makes others braver"],
      humorSignature: "Infectious, physical humor — big energy, big laughs, stories told with full-body commitment",
      growthTrajectory: "Learning the value of stillness after years of constant motion",
      iSharingMarkers: ["Overcoming a physical challenge together", "Spontaneous cooking experiments", "Dancing without caring who's watching"],
    },
    eloScore: 1320,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_14",
    firstName: "Bennett",
    lastName: "Harrison",
    email: "bennett.h@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "1991",
    state: "Virginia",
    height: "5'10\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Reading", "Intellectual discussions", "TV/Movies", "Volunteering", "Podcasts"],
    topCharacteristics: ["Emotionally mature", "Honest", "Empathetic", "Logical", "Patient"],
    socialLink: "https://i.pravatar.cc/400?img=15",
    answers: {
      unconventional_path: "I was a high school English teacher for 5 years before going back to school for clinical psychology. My students taught me more about human behavior than any textbook. Now I specialize in men's mental health — which is wildly underserved and deeply needed.",
      fascination: "Narrative psychology — how the stories we tell about ourselves literally shape our brain structure and behavior. Change someone's story and you change their biology. It's not metaphor; it's neuroscience.",
      humor: "A male client once told me he'd 'never cried in his life.' Fifteen minutes later he was sobbing about his childhood dog. When he stopped, he looked at me and said 'I think that was allergies.' I said 'Your dog was named Biscuit and you're allergic to feelings.' He laughed so hard he cried again.",
      admired_quality: "When someone can hold complexity — believe two contradictory things at once, sit with ambiguity, resist the urge to flatten everything into simple answers.",
      growth_edge: "Allowing myself to be messy. As a therapist, I've internalized this idea that I should have my emotional life perfectly managed. I don't. Nobody does.",
      friend_pitch: "Bennett is the friend who makes everyone feel safe enough to say the thing they've been scared to say. He's genuinely brilliant, unexpectedly hilarious, and the kind of person who makes you feel smarter and braver just by listening to you.",
      prompt_ted_talk: "Why men's emotional literacy is a public health crisis — and what we can actually do about it",
      prompt_controversial: "Therapy culture has overcorrected. Not everything is trauma, not everyone needs to be diagnosed, and sometimes the healthiest thing you can do is just go for a walk and call your mom.",
      prompt_secret_talent: "I do a one-man dramatic reading of an entire Seinfeld episode. All characters, all inflections. It takes 22 minutes and it's devastatingly accurate.",
    },
    vectors: {
      selfExpansion: ["Clinical psychology", "Men's mental health", "Narrative therapy", "Educational background"],
      admirationSignals: ["Bridges teaching and therapy", "Specializes in underserved population", "Holds complexity with grace"],
      humorSignature: "Therapeutic humor — precise, well-timed, and somehow both funny and healing at the same time",
      growthTrajectory: "Learning to let go of the pressure to be perfectly emotionally composed",
      iSharingMarkers: ["Deep conversations that reveal unexpected layers", "Laughing at the absurdity of being human", "Moments of genuine emotional honesty"],
    },
    eloScore: 1440,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_m_15",
    firstName: "Sam",
    lastName: "Nguyen",
    email: "sam.n@example.com",
    gender: "Man",
    seeking: "Women",
    birthYear: "2000",
    state: "Michigan",
    height: "5'8\"",
    education: "Bachelor's",
    exercise: "1-2x/week",
    interests: ["Gaming", "Startups", "Cooking", "TV/Movies", "Intellectual discussions"],
    topCharacteristics: ["Funny", "Creative", "Open-minded", "Logical", "Flexible"],
    socialLink: "https://i.pravatar.cc/400?img=13",
    answers: {
      unconventional_path: "Built an indie video game while working full-time at a grocery store. No game dev degree, just YouTube tutorials and 2 years of weekends. It got featured on Steam and sold 30,000 copies. Used the money to quit and go full indie.",
      fascination: "Procedural generation in game design — how you create infinite unique worlds using math and algorithms. It's like being an architect who designs the laws of physics instead of buildings.",
      humor: "My mom tried to explain my job to her friends and said I 'draw cartoons on the computer for the internet.' When I corrected her she said 'is that not what you do?' And honestly... she's not entirely wrong.",
      admired_quality: "When someone is completely unpretentious about their skills. The best developers I know explain code like they're talking to a friend, not performing intelligence.",
      growth_edge: "Getting outside more and building a social life beyond my computer. I spent so long grinding on my game that my friend group kind of atrophied. Actively rebuilding that.",
      friend_pitch: "Sam is a creative genius who doesn't know he's a creative genius. He'll make you laugh with the most random observations, cook you surprisingly good Vietnamese food from his mom's recipes, and make you wish you could see the world through his weird, wonderful brain.",
      prompt_ted_talk: "How indie games are becoming the most important art form of our generation — and why nobody's paying attention",
      prompt_controversial: "AAA video games are the new Hollywood blockbusters — expensive, formulaic, and afraid to take risks. The real innovation is happening in someone's bedroom with a $0 budget.",
      prompt_secret_talent: "I can cook any Vietnamese dish from memory. My mom drilled the recipes into me before I left for college. It's my love language.",
    },
    vectors: {
      selfExpansion: ["Indie game development", "Procedural world generation", "Vietnamese food culture", "Creative tech"],
      admirationSignals: ["Self-taught game developer success", "Unpretentious creative talent", "Genuine and unassuming"],
      humorSignature: "Quirky, self-deprecating nerd humor — finds absurdity in the gap between his world and 'normal' life",
      growthTrajectory: "Expanding social connections and building a life beyond the screen",
      iSharingMarkers: ["Showing someone your creative work for the first time", "Discovering a weird shared interest", "Cooking together and telling family stories"],
    },
    eloScore: 950,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },

  // ============ WOMEN (15) ============
  {
    id: "seed_w_01",
    firstName: "Maya",
    lastName: "Patel",
    email: "maya.p@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1997",
    state: "California",
    height: "5'4\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Art", "Travel", "Cooking", "Social issues", "Photography"],
    topCharacteristics: ["Creative", "Empathetic", "Ambitious", "Open-minded", "Intuitive"],
    socialLink: "https://i.pravatar.cc/400?img=5",
    answers: {
      unconventional_path: "Left my architecture job to become a UX researcher studying how hospital design affects patient recovery. My boss thought I was crazy. But I'd watched my grandmother suffer in a badly designed ICU and realized that buildings aren't just structures — they're environments that heal or harm.",
      fascination: "The psychology of space — how ceiling height affects creativity, how lighting changes mood, how the distance between your bed and the nearest window predicts your recovery time in a hospital. Design is invisible power.",
      humor: "I was presenting a redesigned hospital layout to a board of surgeons and accidentally projected my Spotify 'Sad Girl Autumn' playlist instead of my slides. One surgeon said 'well, this explains the mood lighting recommendations.' I got the contract.",
      admired_quality: "When someone notices what's invisible to everyone else — the person who's uncomfortable, the detail that's off, the problem nobody named yet. Perception as a superpower.",
      growth_edge: "Setting boundaries with my empathy. I absorb other people's pain like a sponge and I'm learning that I can care deeply without carrying everything.",
      friend_pitch: "Maya sees the world differently than anyone you've ever met — literally. She'll show you beauty in a parking garage, meaning in a floor plan, and she cooks Indian food that'll ruin restaurants for you forever. Also she's hilarious when she's not trying to be.",
      prompt_ted_talk: "How the buildings around you are quietly shaping your mental health — and why architects should study psychology",
      prompt_controversial: "Open floor plan offices are a crime against humanity. Whoever invented them never had to concentrate on anything in their life.",
      prompt_secret_talent: "I can draw any building I've been in from memory, to roughly accurate scale. My spatial memory is borderline photographic.",
    },
    vectors: {
      selfExpansion: ["Healthcare architecture", "Environmental psychology", "Indian cooking", "Design thinking"],
      admirationSignals: ["Bridges architecture and human wellbeing", "Uncommonly perceptive", "Transformed personal pain into systemic solutions"],
      humorSignature: "Accidental humor — funniest when she's being completely genuine, with a gift for timing she doesn't know she has",
      growthTrajectory: "Learning to protect her own energy while maintaining deep empathy for others",
      iSharingMarkers: ["Noticing a beautiful design detail together", "Cooking and sharing cultural traditions", "The moment you see something from a completely new angle"],
    },
    eloScore: 1280,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_02",
    firstName: "Sophie",
    lastName: "Laurent",
    email: "sophie.l@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1995",
    state: "New York",
    height: "5'7\"",
    education: "Master's / JD",
    exercise: "5-6x/week",
    interests: ["Dancing", "Theatre", "Writing", "Social issues", "Travel"],
    topCharacteristics: ["Confident", "Creative", "Spontaneous", "Funny", "Ambitious"],
    socialLink: "https://i.pravatar.cc/400?img=9",
    answers: {
      unconventional_path: "Got an MBA and then immediately became a documentary filmmaker. My business school classmates were baffled. But I realized the most important stories about our economy aren't being told by MBAs — they're being lived by people nobody interviews. My first doc about gig workers got into Tribeca.",
      fascination: "The economics of attention — how our eyeballs became the most valuable commodity in human history and why that changes everything about politics, art, relationships, and what it means to be a person.",
      humor: "I was filming an interview with a very serious CEO and his golden retriever walked in, jumped on his lap, and started licking his face on camera. He tried to maintain composure for about 4 seconds before completely giving up. We used the footage. It's the most-watched clip from the whole documentary.",
      admired_quality: "Fearlessness in self-expression — people who say what they actually think, make the art they actually want to make, and let themselves be genuinely weird without apology.",
      growth_edge: "Patience. I want everything to happen right now. I'm learning that some things need to cook slowly and that urgency is sometimes the enemy of quality.",
      friend_pitch: "Sophie walks into a room and the energy changes. She's brilliant, fearless, and has this way of making everyone around her feel more alive. She'll make you laugh, challenge your assumptions, and probably convince you to do karaoke.",
      prompt_ted_talk: "The attention economy is destroying our ability to love — and what we can do about it",
      prompt_controversial: "Hustle porn is just capitalism dressed up as motivation. The glorification of being busy is making us all miserable and nobody wants to say it out loud.",
      prompt_secret_talent: "I can do a full choreographed dance from any music video from 2005-2015. Beyoncé, Rihanna, Usher — I have them all locked in muscle memory.",
    },
    vectors: {
      selfExpansion: ["Documentary filmmaking", "Attention economics", "Business storytelling", "Dance culture"],
      admirationSignals: ["MBA-to-filmmaker pivot", "Tribeca-featured work", "Fearless creative expression"],
      humorSignature: "Quick, sharp, confident — the humor of someone who's not afraid to take up space",
      growthTrajectory: "Learning to slow down and let quality emerge instead of forcing urgency",
      iSharingMarkers: ["Spontaneous dancing", "Passionate debates about ideas", "Discovering someone's hidden depth"],
    },
    eloScore: 1400,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_03",
    firstName: "Iris",
    lastName: "Nakamura",
    email: "iris.n@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1994",
    state: "Oregon",
    height: "5'3\"",
    education: "Doctorate",
    exercise: "3-4x/week",
    interests: ["Nature", "Reading", "Intellectual discussions", "Craft projects", "Camping"],
    topCharacteristics: ["Patient", "Logical", "Open-minded", "Calm", "Honest"],
    socialLink: "https://i.pravatar.cc/400?img=10",
    answers: {
      unconventional_path: "My PhD committee wanted me to study popular, fundable topics in marine biology. Instead I spent four years studying the communication patterns of octopuses — solitary creatures that everyone said don't communicate. Turns out they do, through color, texture, and posture. My paper changed how we think about invertebrate intelligence.",
      fascination: "Cephalopod cognition — octopuses have distributed intelligence across their eight arms. Each arm can taste, feel, and make independent decisions. It's an alien intelligence on our own planet and we barely understand it.",
      humor: "I was doing fieldwork and an octopus stole my underwater camera, took it into its den, and when we recovered it there were 30 photos of the inside of an octopus den. I published them. Technically the octopus is my co-photographer.",
      admired_quality: "Genuine curiosity — people who ask questions because they actually want to know, not because they want to seem smart. You can always tell the difference.",
      growth_edge: "Being more socially assertive. I'm very comfortable with octopuses and very awkward at parties. Working on bringing some of my research confidence into my personal life.",
      friend_pitch: "Iris is the quietest person in the room and the most interesting. Once you get her talking she'll tell you things about the ocean that completely change how you see the world. She makes the best tea, gives the most thoughtful gifts, and her patience is genuinely superhuman.",
      prompt_ted_talk: "What octopuses can teach us about intelligence, consciousness, and the limits of human understanding",
      prompt_controversial: "We spend billions looking for alien intelligence in space while ignoring genuinely alien minds in our own oceans. The octopus has been solving the hard problem of consciousness for 500 million years.",
      prompt_secret_talent: "I do incredibly detailed scientific illustrations by hand. My field notebooks look like Victorian naturalist journals.",
    },
    vectors: {
      selfExpansion: ["Cephalopod cognition", "Marine biology", "Scientific illustration", "Invertebrate intelligence"],
      admirationSignals: ["Paradigm-shifting research", "Deep patience and observation", "Found communication where others saw silence"],
      humorSignature: "Quiet, dry, nature-nerd humor — deadpan delivery of genuinely wild scientific stories",
      growthTrajectory: "Bringing her professional confidence and curiosity into personal connections",
      iSharingMarkers: ["Sharing a strange nature fact that blows your mind", "Comfortable silence in beautiful places", "The moment someone 'gets' something you care about"],
    },
    eloScore: 1180,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_04",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.s@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1993",
    state: "Texas",
    height: "5'5\"",
    education: "Doctorate",
    exercise: "3-4x/week",
    interests: ["Intellectual discussions", "Volunteering", "Reading", "Cooking", "Podcasts"],
    topCharacteristics: ["Ambitious", "Empathetic", "Honest", "Responsible", "Emotionally mature"],
    socialLink: "https://i.pravatar.cc/400?img=16",
    answers: {
      unconventional_path: "I was the first in my family to go to medical school, and then I chose pediatric oncology — the field everyone warns you away from. My parents wanted me in cardiology where the money is. But I'd volunteered at a children's hospital and those kids changed me. Their courage makes everything else feel small.",
      fascination: "Pediatric palliative care and the philosophy of a 'good death.' It sounds dark but it's actually about quality of life — making sure that however much time someone has, they spend it feeling loved, comfortable, and like themselves.",
      humor: "A 9-year-old patient of mine told me my stethoscope was 'giving doctor costume from Spirit Halloween.' Then she asked if I was 'a real doctor or just doing an internship.' She was right — my stethoscope was cheap. I upgraded.",
      admired_quality: "Resilience that doesn't harden you. People who've been through genuinely difficult things and somehow come out more tender, not less. That's alchemy.",
      growth_edge: "Letting joy in without guilt. My work is heavy and I sometimes feel like I don't deserve to be happy when my patients are suffering. I'm learning that my joy doesn't diminish their struggle.",
      friend_pitch: "Priya is the strongest person I know and she'd never tell you that. She holds families together during the worst moments of their lives and then comes home and makes incredible chai and asks you about your day like she has infinite energy. She does not. But she tries.",
      prompt_ted_talk: "What dying children taught me about how to live — and why we need to stop avoiding conversations about death",
      prompt_controversial: "The American healthcare system treats death as a failure instead of an inevitability. We spend 80% of healthcare dollars in the last months of life making people miserable because we're too afraid to have honest conversations.",
      prompt_secret_talent: "I can do medical origami — I fold paper cranes and animals for my patients. I've made over 2,000 of them. Each one is different.",
    },
    vectors: {
      selfExpansion: ["Pediatric oncology", "Palliative care philosophy", "Medical humanities", "Indian cultural traditions"],
      admirationSignals: ["Chose the hardest path out of compassion", "First-gen physician", "Courage to face daily what others can't imagine"],
      humorSignature: "Warm, resilient humor — finds light in dark places without diminishing the darkness",
      growthTrajectory: "Learning to allow herself joy and rest without guilt",
      iSharingMarkers: ["Conversations about what really matters in life", "Sharing a quiet moment of normalcy", "The relief of being understood by someone who also carries weight"],
    },
    eloScore: 1350,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_05",
    firstName: "Elena",
    lastName: "Vasquez",
    email: "elena.v@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1996",
    state: "Florida",
    height: "5'6\"",
    education: "Bachelor's",
    exercise: "5-6x/week",
    interests: ["Dancing", "Working out", "Cooking", "Fashion", "Travel"],
    topCharacteristics: ["Confident", "Spontaneous", "Funny", "Flexible", "Optimistic"],
    socialLink: "https://i.pravatar.cc/400?img=20",
    answers: {
      unconventional_path: "I was pre-law and hating my life. Started teaching dance fitness classes as a side gig for rent money. Within a year I had 300 students and a waitlist. Dropped out, built it into a studio, and now I run three locations. My parents still ask when I'm going back to school.",
      fascination: "The biomechanics of dance — how different dance styles develop different muscle groups and neural pathways. Salsa develops proprioception, hip-hop develops explosive power, ballet develops sustained tension. Your dance style literally shapes your body and brain.",
      humor: "I accidentally taught an entire Zumba class with my shirt on inside out. Nobody said anything for 45 minutes. When I noticed, one woman in the back yelled 'I thought it was a fashion statement!' I kept it that way for the rest of class.",
      admired_quality: "When someone is completely in their body — not self-conscious, not performing, just fully present in physical space. Athletes, dancers, people who work with their hands. There's something magnetic about embodied confidence.",
      growth_edge: "Emotional depth in relationships. I'm great at energy and fun but I've used that as a way to avoid going deeper. Learning to slow down and be vulnerable instead of always being 'on.'",
      friend_pitch: "Elena is a force of nature. She'll drag you to a dance class and you'll hate the first 10 minutes and love the next 50. She makes everyone around her feel beautiful and capable. She's also way deeper than she lets on — you just have to stay past the party.",
      prompt_ted_talk: "Why movement is the most underrated mental health intervention — and how dance specifically rewires emotional regulation",
      prompt_controversial: "Fitness culture is obsessed with punishment. We've turned movement — which should be joyful — into penance for eating food. Dancing is exercise and nobody has to know.",
      prompt_secret_talent: "I can learn any dance choreography from just watching it once. One viewing, full performance. My students think I'm a robot.",
    },
    vectors: {
      selfExpansion: ["Dance fitness business", "Movement biomechanics", "Latin dance culture", "Body-positive fitness"],
      admirationSignals: ["Built a business from passion and instinct", "Makes others feel capable", "Embodied confidence"],
      humorSignature: "Energetic, physical humor — laughs at herself loudly and brings everyone along for the ride",
      growthTrajectory: "Learning to go deep emotionally instead of staying on the energetic surface",
      iSharingMarkers: ["Dancing together without caring how it looks", "The post-workout endorphin conversation", "Moments of unexpected vulnerability"],
    },
    eloScore: 1100,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_06",
    firstName: "Ava",
    lastName: "Lindgren",
    email: "ava.l@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1995",
    state: "Minnesota",
    height: "5'8\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Nature", "Outdoor sports", "Photography", "Camping", "Writing"],
    topCharacteristics: ["Calm", "Patient", "Honest", "Creative", "Flexible"],
    socialLink: "https://i.pravatar.cc/400?img=23",
    answers: {
      unconventional_path: "Left my environmental law career to become a conservation photographer. I now spend half the year documenting endangered ecosystems — last month I was in the Amazon, next month I'm going to the Arctic. My lawyer friends think I lost my mind. I think I found it.",
      fascination: "The visual language of ecosystems — how you can read the health of a forest by its canopy structure, or predict a river's behavior by its meander patterns. Landscapes are texts if you know how to read them.",
      humor: "I was setting up a camera trap for wolves and a raccoon photobombed every single shot. 300 photos of the same raccoon posing like a model. I submitted one to a photo contest and it won honorable mention. The raccoon has more awards than me.",
      admired_quality: "Steadiness — people who are the same person whether things are going well or badly. You always know where you stand with them and they don't get swept up in drama or hype.",
      growth_edge: "Letting people get close. My lifestyle is nomadic and I've used that as a convenient excuse to keep relationships at arm's length. I'm ready to stop running and let someone in.",
      friend_pitch: "Ava is the person you want to get lost with — literally and figuratively. She sees the world more clearly than anyone I know, takes photos that make you cry, and has this grounding presence that makes everything feel calm. She's also accidentally hilarious.",
      prompt_ted_talk: "Why every person should spend a week alone in a wilderness — and how it changes your relationship with yourself",
      prompt_controversial: "Eco-tourism is mostly greenwashed vacation culture. If you really care about conservation, spend less time visiting beautiful places and more time protecting the ugly ones that nobody wants to see.",
      prompt_secret_talent: "I can identify over 200 bird species by their call alone. My friends find this either impressive or deeply concerning.",
    },
    vectors: {
      selfExpansion: ["Conservation photography", "Wilderness ecology", "Environmental law", "Nomadic lifestyle"],
      admirationSignals: ["Left stability for purpose", "Reads landscapes like texts", "200+ bird calls memorized"],
      humorSignature: "Understated, nature-flavored humor — quiet observations delivered with perfect deadpan",
      growthTrajectory: "Learning to let people close after years of solo wandering",
      iSharingMarkers: ["Silence in wild places", "Spotting wildlife together", "Sharing a moment of awe at something natural"],
    },
    eloScore: 1300,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_07",
    firstName: "Jordan",
    lastName: "Mitchell",
    email: "jordan.m@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1998",
    state: "Georgia",
    height: "5'5\"",
    education: "Bachelor's",
    exercise: "3-4x/week",
    interests: ["Startups", "Podcasts", "Working out", "Intellectual discussions", "Social issues"],
    topCharacteristics: ["Ambitious", "Confident", "Funny", "Logical", "Honest"],
    socialLink: "https://i.pravatar.cc/400?img=25",
    answers: {
      unconventional_path: "Started my first company at 22 — a fintech platform that helps freelancers in developing countries access banking. Everyone said I was too young and the market was too risky. We now serve 50,000 users across 12 countries. Still told I'm too young at every investor meeting.",
      fascination: "Financial inclusion and behavioral economics — how tiny design changes in a banking app can be the difference between someone saving $50 a month or $0. It's not about access, it's about framing.",
      humor: "I pitched to a room of 60-year-old VCs and one asked me if my parents knew I was there. I said 'they're my board members, so yes.' I made it up but they never checked.",
      admired_quality: "When someone backs up their confidence with competence. Talk is cheap. Show me the work, the results, the receipts.",
      growth_edge: "Asking for help. I've built my identity around being self-reliant and I'm learning that interdependence isn't weakness — it's actually harder than doing everything alone.",
      friend_pitch: "Jordan will challenge every assumption you have and you'll thank her for it. She's the smartest person in most rooms, works harder than anyone I know, and still somehow finds time to be a fiercely loyal friend. Also her memes are unmatched.",
      prompt_ted_talk: "Why the global financial system was designed to exclude 2 billion people — and how fintech is rewriting the rules",
      prompt_controversial: "Most DEI initiatives in tech are hiring spectacles. Real inclusion means changing who gets funded, who sets the agenda, and who defines what 'qualified' means.",
      prompt_secret_talent: "I can solve any logic puzzle. My team uses me as a human debugger — if something doesn't make sense, I'll find the flaw in the reasoning.",
    },
    vectors: {
      selfExpansion: ["Fintech innovation", "Global financial inclusion", "Startup leadership", "Behavioral economics"],
      admirationSignals: ["Built international company at 22", "Bridges tech and social impact", "Fierce competence backed by results"],
      humorSignature: "Sharp, quick, power-move humor — uses wit as armor and invitation simultaneously",
      growthTrajectory: "Learning that asking for help is a strength, not a concession",
      iSharingMarkers: ["Solving a hard problem together", "Honest debates where both sides learn", "The moment an idea clicks into place"],
    },
    eloScore: 1220,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_08",
    firstName: "Lily",
    lastName: "Chen",
    email: "lily.c@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1994",
    state: "Massachusetts",
    height: "5'2\"",
    education: "Master's / JD",
    exercise: "1-2x/week",
    interests: ["Musical instruments", "Reading", "Cooking", "Art", "Intellectual discussions"],
    topCharacteristics: ["Emotionally mature", "Patient", "Creative", "Empathetic", "Intuitive"],
    socialLink: "https://i.pravatar.cc/400?img=26",
    answers: {
      unconventional_path: "I was an investment banker and I burned out so completely that I couldn't get out of bed for two months. That breakdown became a breakthrough — I went to music therapy school and now I use piano and composition to help people process trauma. I make 1/5th the money and I'm 10x happier.",
      fascination: "How music activates brain regions that language can't reach. I've worked with stroke patients who can't speak a single word but can sing entire songs. Music bypasses the damaged pathways. It's not magic — it's neuroscience — but it feels like magic.",
      humor: "A patient once told me my piano playing 'sounded like if a sad movie had a baby with a lullaby.' I have never received a more accurate compliment. I'm putting it on my business cards.",
      admired_quality: "Tenderness without weakness. People who are genuinely soft and kind but not pushover-s. Kindness requires more backbone than toughness does.",
      growth_edge: "Trusting my own worth outside of productivity. I spent so long in a culture that measured value in output that I still feel guilty resting. Rewriting that program.",
      friend_pitch: "Lily is the friend who'll sit with you in silence when you're sad and somehow that silence will be the most comforting thing you've ever experienced. She plays piano like an angel, makes dumplings from scratch, and has the emotional intelligence of someone who has genuinely done the inner work.",
      prompt_ted_talk: "What my burnout taught me about the difference between a career and a calling",
      prompt_controversial: "Toxic positivity is more dangerous than sadness. Telling someone to 'look on the bright side' when they're suffering is cruelty wearing a smile.",
      prompt_secret_talent: "I can play any song by ear after hearing it once. Pop, classical, jazz — if I hear it, I can play it within a few minutes.",
    },
    vectors: {
      selfExpansion: ["Music therapy", "Neuroscience of music", "Burnout recovery", "Chinese home cooking"],
      admirationSignals: ["Transformed burnout into purpose", "Bridges neuroscience and art", "Rare emotional depth"],
      humorSignature: "Gentle, poetic humor — finds beauty and absurdity in the same moment",
      growthTrajectory: "Unlearning productivity-as-identity and learning to rest without guilt",
      iSharingMarkers: ["Music that gives you chills", "Comfortable silence that feels like home", "Sharing something vulnerable and being met with grace"],
    },
    eloScore: 1360,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_09",
    firstName: "Nina",
    lastName: "Okafor",
    email: "nina.o@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1996",
    state: "Maryland",
    height: "5'7\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Social issues", "Intellectual discussions", "Writing", "Travel", "Art"],
    topCharacteristics: ["Honest", "Ambitious", "Open-minded", "Empathetic", "Responsible"],
    socialLink: "https://i.pravatar.cc/400?img=29",
    answers: {
      unconventional_path: "Turned down a Supreme Court clerkship to start a legal literacy nonprofit. Everyone said I was wasting the most prestigious opportunity in law. But I'd watched too many people lose in court simply because they didn't understand their rights. Access to justice shouldn't require a law degree.",
      fascination: "The intersection of storytelling and legal advocacy. The best lawyers aren't the ones who know the most law — they're the ones who tell the most compelling stories. Every case is a narrative and the jury is the audience.",
      humor: "I was doing a legal literacy workshop and asked the room 'who knows what habeas corpus means?' A teenager raised his hand and said 'it's when the body has a corpus.' I mean... technically... he's in the zone.",
      admired_quality: "Integrity under pressure — when someone does the right thing when nobody's watching and there's no reward. Especially when it costs them something.",
      growth_edge: "Not trying to save everyone. I have a savior complex and I'm learning that empowerment is more sustainable than rescue.",
      friend_pitch: "Nina is the person you call when you need someone to fight for you — literally and figuratively. She's whip-smart, deeply principled, and will hold you accountable with so much love you don't even mind. Also her Nigerian jollof rice will change your life.",
      prompt_ted_talk: "Why legal literacy should be taught in high school — and how story-based advocacy can close the justice gap",
      prompt_controversial: "The legal system doesn't fail people by accident. It was designed to be inaccessible. Simplifying legal language isn't dumbing it down — it's democratizing power.",
      prompt_secret_talent: "I'm an incredible braider — I can do any style of African hair braiding. I learned from my grandmother and I still braid friends' hair as a form of meditation.",
    },
    vectors: {
      selfExpansion: ["Legal literacy", "Advocacy storytelling", "Nigerian culture", "Social justice systems"],
      admirationSignals: ["Turned down Supreme Court for principle", "Bridges law and community", "Fierce integrity"],
      humorSignature: "Sharp, warm, educator humor — makes complex things accessible and funny simultaneously",
      growthTrajectory: "Shifting from rescue to empowerment — learning sustainable forms of care",
      iSharingMarkers: ["Passionate debates about justice", "Sharing cultural traditions", "The satisfaction of helping someone understand something"],
    },
    eloScore: 1420,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_10",
    firstName: "Carmen",
    lastName: "Delgado",
    email: "carmen.d@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1992",
    state: "New Mexico",
    height: "5'4\"",
    education: "Bachelor's",
    exercise: "1-2x/week",
    interests: ["Craft projects", "Art", "Cooking", "Museums", "Nature"],
    topCharacteristics: ["Creative", "Patient", "Calm", "Intuitive", "Flexible"],
    socialLink: "https://i.pravatar.cc/400?img=32",
    answers: {
      unconventional_path: "I'm a ceramic artist who spent three years in Oaxaca learning from indigenous potters. My MFA program thought I should be making conceptual installation art for galleries. Instead I apprenticed with women who've been making functional pottery for generations. My work now bridges both worlds.",
      fascination: "The chemistry of glazes — how tiny variations in mineral composition create completely different colors at different temperatures. It's alchemy. You mix earth and fire and time and something beautiful emerges that you couldn't have fully predicted.",
      humor: "I was doing a pottery demo at a festival and a kid asked me to make a dragon. I made what I thought was a very respectable dragon. He looked at it and said 'that's a dog.' Fair.",
      admired_quality: "Dedication to slow, unglamorous work. The people I admire most aren't the ones who had viral moments — they're the ones who showed up to their craft every single day for decades.",
      growth_edge: "Being more assertive about the value of my work. Artists are conditioned to undercharge and over-explain. I'm learning to name my prices without apologizing.",
      friend_pitch: "Carmen is the most centered person I know. She moves through life at her own pace and everything she touches becomes more beautiful. She'll teach you to see art in dirt, cook you something incredible from her garden, and make you feel completely unhurried. In a world of noise, she's the quiet.",
      prompt_ted_talk: "What indigenous pottery traditions teach us about patience, community, and why slow art matters in a fast world",
      prompt_controversial: "The art world's obsession with novelty has made us forget that craft IS art. A perfectly thrown bowl that holds soup is as valid as anything in a museum. Maybe more so.",
      prompt_secret_talent: "I can identify clay types by taste. Yes, taste. Different clays have different mineral compositions and you can tell them apart on your tongue. Potters have been doing this for millennia.",
    },
    vectors: {
      selfExpansion: ["Ceramic arts", "Indigenous pottery traditions", "Glaze chemistry", "Oaxacan culture"],
      admirationSignals: ["Cross-cultural apprenticeship", "Bridges traditional and contemporary art", "Dedicated to slow mastery"],
      humorSignature: "Gentle, understated humor — the quiet funny that sneaks up on you and lingers",
      growthTrajectory: "Learning to advocate for the economic value of her art and time",
      iSharingMarkers: ["Making something with your hands", "The moment a glaze reveals itself after firing", "Unhurried conversation over handmade food"],
    },
    eloScore: 1050,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_11",
    firstName: "Zara",
    lastName: "Ahmed",
    email: "zara.a@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "2000",
    state: "New York",
    height: "5'6\"",
    education: "Bachelor's",
    exercise: "3-4x/week",
    interests: ["Fashion", "Photography", "Travel", "Art", "Social issues"],
    topCharacteristics: ["Creative", "Confident", "Spontaneous", "Open-minded", "Ambitious"],
    socialLink: "https://i.pravatar.cc/400?img=34",
    answers: {
      unconventional_path: "Started a sustainable fashion brand using deadstock fabric from luxury houses. I was 21 and had no fashion industry connections. Cold-emailed 200 people. Got 199 rejections and one person who believed in me. That one person connected me to a fabric warehouse and now we've diverted 15 tons of textile waste from landfills.",
      fascination: "The environmental impact of fashion — the fashion industry produces 10% of global carbon emissions, more than international flights and maritime shipping combined. Most people have no idea their closet is a climate issue.",
      humor: "I was at a fashion week party and someone asked who I was wearing. I said 'curtains from a hotel in Marrakech.' They said 'which designer?' I said 'no, literally hotel curtains. I made this dress from hotel curtains.' They thought I was joking. I was not.",
      admired_quality: "Creative resourcefulness — making something beautiful from constraints. Anyone can create with unlimited resources. Show me what you do with limitations.",
      growth_edge: "Slowing down my decision-making. I'm very instinct-driven and usually right, but when I'm wrong, I'm spectacularly wrong because I didn't take time to think it through.",
      friend_pitch: "Zara is the most resourceful person alive. She'll make you a stunning outfit from a thrift store, take you to a hidden rooftop you didn't know existed, and somehow know someone at every restaurant in the city. She moves fast and thinks big and she makes you feel like anything is possible.",
      prompt_ted_talk: "Why your closet is the most impactful place to fight climate change — and it doesn't have to cost more",
      prompt_controversial: "Fast fashion is an ethical catastrophe that we're all complicit in, and 'sustainable fashion' that costs $300 for a t-shirt isn't the answer either. We need a middle ground and the industry is allergic to finding it.",
      prompt_secret_talent: "I can drape fabric on a mannequin and create a wearable garment in about 20 minutes, no pattern needed. I think in three dimensions.",
    },
    vectors: {
      selfExpansion: ["Sustainable fashion", "Textile recycling", "Global fashion culture", "Creative entrepreneurship"],
      admirationSignals: ["Built brand from 199 rejections", "Environmental impact at scale", "Creates beauty from waste"],
      humorSignature: "Deadpan confidence humor — says outrageous true things with a completely straight face",
      growthTrajectory: "Learning to balance instinct with deliberation in high-stakes decisions",
      iSharingMarkers: ["Discovering hidden gems in a city", "Creating something from nothing", "The thrill of an unconventional solution"],
    },
    eloScore: 990,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_12",
    firstName: "Hana",
    lastName: "Kowalski",
    email: "hana.k@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1997",
    state: "Colorado",
    height: "5'5\"",
    education: "Associate degree",
    exercise: "Daily",
    interests: ["Outdoor sports", "Cooking", "Nature", "Working out", "Camping"],
    topCharacteristics: ["Optimistic", "Spontaneous", "Honest", "Confident", "Flexible"],
    socialLink: "https://i.pravatar.cc/400?img=38",
    answers: {
      unconventional_path: "Skipped college to become a pastry chef, then left restaurant life to start a bakery that hires formerly incarcerated women. My parents are Polish immigrants who wanted me to be a doctor. I'm teaching women to make croissants and rebuild their lives. Close enough.",
      fascination: "The science of lamination — how you create 729 layers of butter and dough in a croissant through a precise sequence of folds. It's engineering disguised as baking. One degree of temperature off and everything fails.",
      humor: "A customer once returned a croissant because it was 'too flaky.' I stared at her for a full five seconds trying to figure out if it was a compliment. It was not. She wanted a dense croissant. I still think about it.",
      admired_quality: "Grit without grimness. People who work incredibly hard but haven't lost their lightness. You can be driven and still laugh easily.",
      growth_edge: "Accepting imperfection. In baking, precision matters — but I apply that standard to everything and it makes me rigid. Learning that life doesn't need to be 729 perfect layers.",
      friend_pitch: "Hana will outrun you, out-bake you, and out-optimism you. She's built something beautiful from scratch — both literally and figuratively — and she'll make you believe you can too. Also, her croissants are a religious experience.",
      prompt_ted_talk: "How a croissant can change a life — the unexpected power of teaching craft to people rebuilding from scratch",
      prompt_controversial: "The bakery-as-lifestyle-brand thing is killing real bakeries. Nobody needs a $7 cookie with calligraphy on it. Baking should be accessible, delicious, and unpretentious.",
      prompt_secret_talent: "I can run a sub-3:30 marathon. I trained for my first one to prove I could do something besides bake. Now I can't stop.",
    },
    vectors: {
      selfExpansion: ["Artisan baking", "Social enterprise", "Ultra-endurance running", "Polish-American culture"],
      admirationSignals: ["Bakery as social impact vehicle", "Extreme physical discipline", "Turned unconventional path into purpose"],
      humorSignature: "Bright, punchy humor — quick one-liners delivered with the confidence of someone who knows exactly who she is",
      growthTrajectory: "Learning to let go of perfectionism and accept the beauty of imperfection",
      iSharingMarkers: ["Morning runs in beautiful places", "The satisfaction of making something delicious together", "Pushing through something hard and laughing about it after"],
    },
    eloScore: 1240,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_13",
    firstName: "Olivia",
    lastName: "Torres",
    email: "olivia.t@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1990",
    state: "Illinois",
    height: "5'9\"",
    education: "Master's / JD",
    exercise: "3-4x/week",
    interests: ["Intellectual discussions", "Startups", "Reading", "Travel", "Volunteering"],
    topCharacteristics: ["Ambitious", "Logical", "Responsible", "Honest", "Emotionally mature"],
    socialLink: "https://i.pravatar.cc/400?img=44",
    answers: {
      unconventional_path: "Left McKinsey to run a $200M education foundation. My consulting peers thought I was taking a demotion. But I'd spent three years advising school districts and realized I wanted to actually build the solutions instead of just recommending them. We've redesigned curriculum for 500 schools.",
      fascination: "The science of learning transfer — why students can ace a test and completely fail to apply the knowledge in real life. The gap between what we test and what we actually need people to know is enormous and nobody's talking about it.",
      humor: "I was presenting to a school board and my slide deck got mixed up with someone else's. I spent 30 seconds very confidently presenting someone's vacation photos from Cancun before I realized. The board gave me credit for 'creative opening.'",
      admired_quality: "Strategic patience — people who can see five moves ahead but don't feel the need to rush. Chess thinking applied to life. Plans that unfold over years, not quarters.",
      growth_edge: "Being less guarded emotionally. I'm excellent at professional vulnerability — telling a room of 500 people about my failures. But one-on-one emotional intimacy terrifies me.",
      friend_pitch: "Olivia is the most strategic thinker you'll ever meet who also genuinely cares about people. She'll help you see the bigger picture of your own life, connect you with exactly the right person, and somehow make you feel both challenged and supported at the same time.",
      prompt_ted_talk: "Why we're measuring learning all wrong — and what the science of transfer tells us about building a better education system",
      prompt_controversial: "Standardized testing has done more damage to education than any single policy in American history. We optimized for measurement and forgot about learning.",
      prompt_secret_talent: "I can speed-read. Not the fake kind — I genuinely process about 800 words per minute with full comprehension. I read about 150 books a year.",
    },
    vectors: {
      selfExpansion: ["Education reform", "Learning science", "Foundation leadership", "Strategic consulting"],
      admirationSignals: ["Chose impact over prestige at scale", "Strategic patience", "Redesigned education for 500 schools"],
      humorSignature: "Polished, confident humor — the kind of funny that commands a room without trying to",
      growthTrajectory: "Learning to be as emotionally open in relationships as she is professionally",
      iSharingMarkers: ["Book recommendations that change how you think", "Strategic conversations about the future", "Rare moments of genuine emotional openness"],
    },
    eloScore: 1450,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_14",
    firstName: "Stella",
    lastName: "Petrova",
    email: "stella.p@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1996",
    state: "Pennsylvania",
    height: "5'6\"",
    education: "Bachelor's",
    exercise: "3-4x/week",
    interests: ["Theatre", "Singing", "Travel", "Cooking", "Museums"],
    topCharacteristics: ["Creative", "Spontaneous", "Extroverted", "Funny", "Optimistic"],
    socialLink: "https://i.pravatar.cc/400?img=47",
    answers: {
      unconventional_path: "I was studying chemical engineering and accidentally got cast in a student play. Quit engineering, moved to New York with $800, and spent three years waiting tables while auditioning. Just got cast as the lead in an off-Broadway show. My engineering friends make 3x my salary but none of them cry-laugh at work the way I do.",
      fascination: "Method acting and empathy — how inhabiting someone else's experience literally changes your neural pathways. Actors develop greater emotional intelligence and perspective-taking ability. It's empathy as a trainable skill.",
      humor: "I was doing a dramatic monologue in an audition and my stomach growled so loudly the casting director stopped me and asked if I needed a sandwich. I said 'my character is also hungry.' They called back. The sandwich won them over.",
      admired_quality: "Full commitment to a moment. When someone is so present that they're not thinking about what comes next — they're completely in this conversation, this experience, this laugh. Actors call it 'being in the scene.'",
      growth_edge: "Financial stability and planning for the future. I've been living audition-to-audition and I need to build more structure without losing the spontaneity that makes my life feel alive.",
      friend_pitch: "Stella makes the mundane feel magical. She'll turn a grocery run into an adventure, do accents at dinner that make you spit out your wine, and listen to you with the kind of intensity that makes you feel like the most interesting person in the world. Because to her, in that moment, you are.",
      prompt_ted_talk: "How acting teaches empathy — and why everyone should take an improv class before getting married",
      prompt_controversial: "Social media has made us all performers but none of us are actually present. We're so busy curating our lives that we've forgotten how to experience them.",
      prompt_secret_talent: "I speak four languages — English, Russian, French, and enough Italian to get by. Each one gives me a different personality, which is very confusing for my therapist.",
    },
    vectors: {
      selfExpansion: ["Theatre and acting", "Multilingual culture", "Method acting psychology", "Off-Broadway arts"],
      admirationSignals: ["Risked everything for her art", "Genuine emotional bravery", "Inhabits every moment fully"],
      humorSignature: "Performative and character-driven — can become anyone at a moment's notice, uses voices and accents",
      growthTrajectory: "Building financial and personal stability without losing artistic spontaneity",
      iSharingMarkers: ["Completely losing yourself in a moment together", "Laughing until it hurts", "Sharing something you've never told anyone"],
    },
    eloScore: 1130,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed_w_15",
    firstName: "Vivian",
    lastName: "Thornton",
    email: "vivian.t@example.com",
    gender: "Woman",
    seeking: "Men",
    birthYear: "1993",
    state: "North Carolina",
    height: "5'7\"",
    education: "Master's / JD",
    exercise: "5-6x/week",
    interests: ["Working out", "Reading", "Intellectual discussions", "Startups", "Art"],
    topCharacteristics: ["Ambitious", "Confident", "Emotionally mature", "Responsible", "Honest"],
    socialLink: "https://i.pravatar.cc/400?img=49",
    answers: {
      unconventional_path: "Was a Division I track athlete and tore my ACL junior year. Everyone expected me to spiral. Instead I started coaching youth track in my community during recovery. Realized I was a better coach than competitor. Now I run a nonprofit that uses athletics to teach leadership to girls in underserved communities.",
      fascination: "Sports psychology and the science of choking under pressure. Why do elite athletes fail at the exact moment the stakes are highest? It's a paradox of attention — the harder you try, the worse you perform. The solution is counterintuitive: you have to let go.",
      humor: "I was demonstrating proper hurdle form for my students and absolutely ate it in front of 30 teenagers. Full yard sale. A 13-year-old helped me up and said 'Coach, maybe you should demonstrate what NOT to do.' I said 'that was the plan.' It was not.",
      admired_quality: "Disciplined kindness — people who choose to be generous and compassionate not because it's easy but because they've decided that's who they are. Kindness as a practice, not a personality trait.",
      growth_edge: "Receiving love without trying to earn it. My identity has been tied to achievement for so long that I sometimes don't believe people love me for who I am rather than what I do.",
      friend_pitch: "Vivian is the person who'll run 6 miles with you before dawn, hold your hand through a hard conversation at noon, and give you the most honest feedback you've ever received over dinner — and somehow you'll thank her for all of it. She makes everyone around her better.",
      prompt_ted_talk: "Why every girl deserves a coach — and how athletics teaches the leadership skills school doesn't",
      prompt_controversial: "We tell girls they can do anything but we don't give them the physical confidence to believe it. Until a girl trusts her body, she won't fully trust her mind.",
      prompt_secret_talent: "I paint. Oils, mostly. Nobody expects the jock to also be a painter but some of the best thinking I do happens with a brush in my hand.",
    },
    vectors: {
      selfExpansion: ["Youth athletics coaching", "Sports psychology", "Leadership development", "Oil painting"],
      admirationSignals: ["Transformed setback into purpose", "Bridges athletics and empowerment", "Disciplined kindness as practice"],
      humorSignature: "Self-aware, physical humor — comfortable laughing at herself with confidence that's earned, not performed",
      growthTrajectory: "Learning to be loved for who she is, not just what she accomplishes",
      iSharingMarkers: ["Pushing through something hard together", "Quiet creative moments after high-energy days", "Witnessing someone discover their own strength"],
    },
    eloScore: 1380,
    eloInteractions: 0,
    createdAt: new Date().toISOString(),
  },
];

export function getSeedProfiles(): Profile[] {
  return SEED_PROFILES;
}

export function seedDatabase(): { total: number; men: number; women: number } {
  let men = 0;
  let women = 0;
  for (const profile of SEED_PROFILES) {
    saveProfile(profile);
    if (profile.gender === "Man") men++;
    else women++;
  }
  return { total: SEED_PROFILES.length, men, women };
}

let seeded = false;
export function ensureSeeded() {
  if (!seeded) {
    seedDatabase();
    seeded = true;
  }
}
