import Link from "next/link";

export const metadata = {
  title: "Terms of Service — People Like You",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-stone-50 to-white">
      <div className="mx-auto max-w-2xl px-6 py-24">
        <Link href="/" className="text-sm font-medium text-stone-400 transition hover:text-stone-600">
          &larr; Back
        </Link>

        <h1 className="mt-8 text-3xl font-bold tracking-tight text-stone-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-stone-400">Last updated: March 2026</p>

        <div className="mt-10 space-y-8 text-base leading-7 text-stone-600">
          <section>
            <h2 className="text-lg font-semibold text-stone-900">Welcome to People Like You</h2>
            <p className="mt-3">
              By creating an account or using People Like You (&ldquo;PLY,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;), you agree to these terms. If you don&rsquo;t agree, don&rsquo;t use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Eligibility</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>You must be at least 18 years old.</li>
              <li>You must provide accurate information about yourself.</li>
              <li>One account per person. No fake profiles.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Your account</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>You&rsquo;re responsible for keeping your login credentials secure.</li>
              <li>Everything you share (voice memos, photos, preferences) must be about you and truthful.</li>
              <li>You can delete your account at any time from your settings. Deletion is permanent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">What you can&rsquo;t do</h2>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>Harass, threaten, or abuse other users.</li>
              <li>Impersonate someone else or create fake profiles.</li>
              <li>Use the service for anything illegal.</li>
              <li>Scrape, bot, or automate interactions with the service.</li>
              <li>Share other users&rsquo; private information outside the app.</li>
              <li>Upload content that&rsquo;s violent, hateful, sexually explicit, or illegal.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Your content</h2>
            <p className="mt-3">
              You own your voice recordings, photos, and profile content. By using PLY, you grant us a license to process, store, and display your content for the purpose of providing the service (matching, introductions, profile display). We don&rsquo;t use your content for advertising or sell it to third parties.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">AI-generated content</h2>
            <p className="mt-3">
              Match introductions and personality insights are generated by AI based on your voice memos and profile data. These are our best interpretation of your personality &mdash; they&rsquo;re not perfect. You can flag inaccuracies during profile reveal, and we&rsquo;ll adjust.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Safety</h2>
            <p className="mt-3">
              We take safety seriously. If you experience harassment or feel unsafe, report it immediately. We reserve the right to suspend or terminate accounts that violate these terms or pose a safety risk. Meeting someone in person is always at your own risk &mdash; use common sense and meet in public places.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Service availability</h2>
            <p className="mt-3">
              PLY is provided &ldquo;as is.&rdquo; We don&rsquo;t guarantee uninterrupted service, perfect matches, or romantic outcomes. We&rsquo;re building something new and things may break. We&rsquo;ll do our best to fix them quickly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Changes to these terms</h2>
            <p className="mt-3">
              We may update these terms. If we make significant changes, we&rsquo;ll notify you in the app. Continued use after changes means you accept the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">Contact</h2>
            <p className="mt-3">
              Questions? Email us at{" "}
              <a href="mailto:hello@people-like-you.com" className="text-stone-900 underline">hello@people-like-you.com</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
